version: "3.9"
services:
  backend1:
    image: loadbalancing-backend:latest
    volumes:
      - ./runtime/transformations:/usr/share/loadbalancing-backend/transformations
    hostname: backend1.local
    network_mode: bridge
    ports:
      - "9001:8000"
    environment:
      - PORT=9090
      - SERVER_ID=Server1
      - FRONTEND_HOST=frontend.local
      - FRONTEND_PORT=8080
  backend2:
    image: loadbalancing-backend:latest
    volumes:
      - ./runtime/transformations:/usr/share/loadbalancing-backend/transformations
    hostname: backend2.local
    network_mode: bridge
    ports:
      - "9002:8000"
    environment:
      - PORT=9090
      - SERVER_ID=Server2
      - FRONTEND_HOST=frontend.local
      - FRONTEND_PORT=8080      
  backend3:
    image: loadbalancing-backend:latest
    volumes:
      - ./runtime/transformations:/usr/share/loadbalancing-backend/transformations
    hostname: backend3.local
    network_mode: bridge
    ports:
      - "9003:8000"
    environment:
      - PORT=9090
      - SERVER_ID=Server3
      - FRONTEND_HOST=frontend.local
      - FRONTEND_PORT=8080      
  frontend:
    image: loadbalancing-frontend:latest
    volumes:
      - ./runtime/data:/usr/share/loadbalancing-frontend/data
    hostname: frontend.local
    network_mode: bridge
    ports:
      - "9000:8000"
    environment:
      - PORT=8080
      - BACKENDS="backend1.local:9090 backend2.local:9090 backend3.local:9090"